/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Sharma
 */
public class AdminSection extends javax.swing.JFrame {

    /**
     * Creates new form AdminSection
     */
    public AdminSection() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miProfileChangePassword = new javax.swing.JMenuItem();
        miProfileExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        miMastersCourse = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        miStudentStudentManagement = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Profile");

        miProfileChangePassword.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        miProfileChangePassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/circle.GIF"))); // NOI18N
        miProfileChangePassword.setText("Change Password");
        miProfileChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miProfileChangePasswordActionPerformed(evt);
            }
        });
        jMenu1.add(miProfileChangePassword);

        miProfileExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        miProfileExit.setText("Exit");
        miProfileExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miProfileExitActionPerformed(evt);
            }
        });
        jMenu1.add(miProfileExit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Masters");

        miMastersCourse.setText("Course Management");
        miMastersCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miMastersCourseActionPerformed(evt);
            }
        });
        jMenu2.add(miMastersCourse);

        jMenuItem1.setText("View All Courses");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Enquiry");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Student");

        miStudentStudentManagement.setText("Student Management");
        miStudentStudentManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miStudentStudentManagementActionPerformed(evt);
            }
        });
        jMenu4.add(miStudentStudentManagement);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miProfileExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miProfileExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_miProfileExitActionPerformed

    private void miProfileChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miProfileChangePasswordActionPerformed
       new ChangeAdminPasswordForm().setVisible(true);
    }//GEN-LAST:event_miProfileChangePasswordActionPerformed

    private void miMastersCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miMastersCourseActionPerformed
        new CourseForm().setVisible(true);
    }//GEN-LAST:event_miMastersCourseActionPerformed

    private void miStudentStudentManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miStudentStudentManagementActionPerformed
        new StudentForm().setVisible(true);
    }//GEN-LAST:event_miStudentStudentManagementActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        new ViewAllCourseForm().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem miMastersCourse;
    private javax.swing.JMenuItem miProfileChangePassword;
    private javax.swing.JMenuItem miProfileExit;
    private javax.swing.JMenuItem miStudentStudentManagement;
    // End of variables declaration//GEN-END:variables
}
